sensor_kit_base_link:
  # Velodyne LIDAR
  lidar_top:
    x: 0.177
    y: 0.0
    z: 0.620
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # ZED2 Kameralar (sadece görüntü, IMU kaldırıldı)
  traffic_light_left_camera:
    x: 0.205
    y: 0.060
    z: 0.685
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  traffic_light_right_camera:
    x: 0.205
    y: -0.060
    z: 0.685
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # ZED2 IMU KALDIRILDI

  # Xsens GNSS/IMU
  gnss_link:
    x: -1.440
    y: 0.0
    z: 1.390
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # Xsens IMU
  tamagawa/imu_link:
    x: -1.440
    y: 0.0
    z: 1.390
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
